iwlwifi: modify hardware check
When checking which hardware is being talked to, use runtime information
instead of compile time information. This prevents trouble if the
particular hardware is not compiled in.

This fixes the current build error of:
ERROR: "iwl4965_agn_cfg" [drivers/net/wireless/iwlwifi/iwlagn.ko] undefined!

Signed-off-by: Reinette Chatre <reinette.chatre@intel.com>